# -*- coding: utf-8 -*-
"""Project 9 - Number Guessing Game

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OG11E01OgvcqrAbyj4QqazCf6UddIA4p
"""

from IPython.lib.display import join
import random

print("Guess a number 1-5")

def get_random_integer():
  return random.randint(1, 5)

Attempts = 0

while Attempts < 7:

 User_Input = input("Guess a number: ")
 Integer = get_random_integer()
 print(Integer)

 if int(User_Input) == Integer:
    print(Integer)
    print("That is correct!")
    break

 elif Attempts < 7:
  Attempts += 1
  print("Incorrect. Guess again.")

if Attempts >= 7:
 print("Game over!")



print("Thank you for playing!")